#!/usr/bin/env python3
"""Read campaign page views from FrontDoor's Cloudflare D1 database."""
import argparse
from datetime import date, datetime, time, timezone
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
from zoneinfo import ZoneInfo

LOCAL = ZoneInfo('America/Chicago')
DEFAULT_REPO = Path(__file__).resolve().parents[4]


def start_date(value):
    try:
        result = date.fromisoformat(value)
        if result.isoformat() != value:
            raise ValueError
        if result > datetime.now(LOCAL).date():
            raise ValueError
        return result
    except ValueError:
        raise argparse.ArgumentTypeError('Use YYYY-MM-DD, today or earlier.') from None


def query(day, end):
    start = datetime.combine(day, time.min, LOCAL).astimezone(timezone.utc)
    # Both timestamps are generated by datetime, never interpolated from raw input.
    return f"""SELECT practice_slug, utm_campaign, city, region, region_code, country,
 COUNT(*) AS page_views,
 COUNT(DISTINCT NULLIF(session_id, '')) AS sessions,
 COUNT(DISTINCT NULLIF(visitor_id, '')) AS browser_ids,
 SUM(CASE WHEN NULLIF(session_id, '') IS NULL THEN 1 ELSE 0 END) AS views_without_session,
 SUM(CASE WHEN NULLIF(visitor_id, '') IS NULL THEN 1 ELSE 0 END) AS views_without_browser,
 MIN(created_at) AS first_utc, MAX(created_at) AS last_utc
FROM events
WHERE created_at >= '{start.strftime('%Y-%m-%d %H:%M:%S')}'
 AND created_at <= '{end.strftime('%Y-%m-%d %H:%M:%S')}'
 AND event_type = 'page_view'
 AND (practice_slug = 'drdronavalli' OR page_path LIKE '/previews/%')
 AND NULLIF(TRIM(utm_campaign), '') IS NOT NULL
 AND LOWER(TRIM(utm_campaign)) != 'test'
GROUP BY practice_slug, utm_campaign, city, region, region_code, country
ORDER BY practice_slug, page_views DESC, city;"""


def local_time(value):
    return datetime.fromisoformat(value.replace('Z', '+00:00')).replace(
        tzinfo=timezone.utc).astimezone(LOCAL).strftime('%Y-%m-%d %H:%M:%S %Z')


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('start_date', type=start_date, help='Inclusive Austin calendar date: YYYY-MM-DD')
    parser.add_argument('--json', action='store_true', help='Print structured results')
    parser.add_argument('--repo', type=Path, default=DEFAULT_REPO, help='FrontDoor previews repository')
    args = parser.parse_args(argv)
    worker = args.repo.resolve() / 'analytics-worker'
    wrangler = worker / 'node_modules/.bin/wrangler'
    if not wrangler.is_file():
        parser.error(f'Wrangler is missing: {wrangler}. Install the analytics-worker dependencies first.')
    end = datetime.now(timezone.utc)
    env = os.environ.copy()
    env['WRANGLER_LOG_PATH'] = str(Path(tempfile.gettempdir()) / 'frontdoor-check-visits.log')
    try:
        result = subprocess.run(
            [str(wrangler), 'd1', 'execute', 'frontdoor_analytics', '--remote',
             '--json', '--command', query(args.start_date, end)],
            cwd=worker, env=env, capture_output=True, text=True, timeout=90)
        if result.returncode:
            # Cloudflare errors are useful, but never print environment values.
            print(result.stderr or result.stdout or 'Cloudflare query failed.', file=sys.stderr)
            return 1
        responses = json.loads(result.stdout)
        if not isinstance(responses, list) or not responses or any(
                item.get('success') is not True for item in responses):
            raise ValueError('Cloudflare did not return a successful query response.')
        rows = [row for item in responses for row in item['results']]
        for row in rows:
            row['first_local'] = local_time(row['first_utc'])
            row['last_local'] = local_time(row['last_utc'])
    except (OSError, subprocess.TimeoutExpired, ValueError, KeyError, TypeError) as exc:
        print(f'Could not read visits: {exc}', file=sys.stderr)
        return 1
    report = {
        'start_date': args.start_date.isoformat(), 'timezone': str(LOCAL),
        'queried_at_utc': end.isoformat(),
        'excluded_campaigns': ['test', '(missing/blank)'],
        'total_page_views': sum(row['page_views'] for row in rows), 'rows': rows,
    }
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(f"Since {args.start_date} 00:00 America/Chicago through {end.astimezone(LOCAL):%Y-%m-%d %H:%M:%S %Z}")
        print('Excluded: test (case-insensitive exact match), and missing/blank campaigns.\n')
        print('Site | Campaign | City, State | Views | Sessions | Browser IDs | Last visit')
        for row in rows:
            print(f"{row['practice_slug']} | {row['utm_campaign']} | {row['city'] or 'Unknown'}, {row['region'] or row['region_code'] or 'Unknown'} | {row['page_views']} | {row['sessions']} | {row['browser_ids']} | {row['last_local']}")
        print(f"\nTotal: {report['total_page_views']} page views.")
        if not rows:
            print('No matching campaign page views were recorded.')
        print('Locations are approximate. Browser IDs are not verified people. Counts per row must not be summed as unique visitors.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
